M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2024-07-04T16:52:01+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-04T16:52:01+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X141.225Y-87.225
X172.35Y-113.95
M30
